### PR TITLE
Java test

### PR DESCRIPTION
**Pull request by z49**
pull!

### CODE REVIEW

**Comment by krs013** [comment]
Wait--sorry, I'm confused. Is this going to overwrite the python code in the master branch with java?

**Comment by bsngardner** [comment]
I hope not, I think it was an accident?

**Comment by krs013** [comment]
See my reply to the email you just sent. I hope not all of the users on github are subscribed to these. If you are, I’ll go curate the list.

On Aug 7, 2015, at 5:08 PM, bsngardner notifications@github.com wrote:

I hope not, I think it was an accident?

**Comment by krs013** [comment]
Nope. We’re good. This list is just the 3 of us.

On Aug 7, 2015, at 5:09 PM, Kristian Sims kristian.sims@gmail.com wrote:

See my reply to the email you just sent. I hope not all of the users on github are subscribed to these. If you are, I’ll go curate the list.

On Aug 7, 2015, at 5:08 PM, bsngardner <notifications@github.com <mailto:notifications@github.com>> wrote:

I hope not, I think it was an accident?

**Comment by z49** [comment]
No! It's github doing things it shouldn't. _angrily waves fist at github Windows GUI and looks for gitshell_

--- Original Message ---

**Pull request closed without merging**
